### ISSUE TITLE
Update NAb methods: Add template language for inclusion criteria for AUC-mb analysis

### ISSUE THREAD

**Issue by monicagerber** [FredHutch/VISCtemplates#102]
## Location

inst/templates/methods-nab/nab-statistical-methods.Rmd

## Old 

The template currently doesn't have any language for this.

## New

Alicia suggested we add language here, but we will need to decide on appropriate methods first.
This came up in review of the NAb template: https://github.com/FredHutch/VISCtemplates/pull/99/files#r796188949

## Justification

Alicia said that she noticed differences across the VISC team and compared to HVTN reports.

**Comment by mayerbry** [comment]
Completed #99
