### ISSUE TITLE
Update visc analysis project vignette for SSH protocol

### ISSUE THREAD

**Issue by at-crx** [FredHutch/VISCtemplates#104]
## Location
vignettes/create_a_visc_analysis_project.Rmd

## Old 

Step 2: Github currently has instructions mentioning setting up a personal access token (PAT), which is HTTPS only 

## New

Update the section with instructions on using SSH keys instead

## Justification
Alicia mentioned that HTTPS is no longer supported

**Comment by slager** [comment]
HTTPS and SSH are both still fully supported by GitHub.

The usethis project recommends HTTPS:
https://usethis.r-lib.org/articles/git-credentials.html

You can set up a GitHub PAT for use with HTTPS here:
https://github.com/settings/tokens

You can add a SSH key here:
https://github.com/settings/keys
