### ISSUE TITLE
Add tests for data version, sha, and branch

### ISSUE THREAD

**Issue by celiaeddy** [FredHutch/VISCtemplates#108]
Discussion from TioT 10/13/22: 

we need to add a table to the PT report template(s) that tests whether SRAs have the correct data version and branch installed. This code should be in a chunk following the data installation code chunk.

example code in [Marie's presentation](https://fredhutch-my.sharepoint.com/:p:/g/personal/mvendett_fredhutch_org/EfzPo8bKyC9MhKzd9i3oaYEBUismwuLWxvejhBW7iSygEA?e=du3WjE)

**Comment by slager** [comment]
See comment in linked PR.
