### ISSUE TITLE
Instructions for vidd-visc team and branch protection

### ISSUE THREAD

**Issue by monicagerber** [FredHutch/VISCtemplates#11]
Add to README:
* does vidd-visc have admin privileges? or just certain people?
* how to set up protection for master branch?

**Comment by clbennet** [comment]
https://ghost.org/blog/prevent-master-push/

**Comment by clbennet** [comment]
Or: https://gist.github.com/tiesmaster/ffd4f4a8b4dd2c127516c93af6cc7b46

**Comment by monicagerber** [comment]
Added info on branch protection rules to release branch
