### ISSUE TITLE
Adding to gitignore file

### ISSUE THREAD

**Issue by wfulp** [FredHutch/VISCtemplates#12]
Can we add these three things to gitignore?

```
.Rhistory
.RData
.Ruserdata
```

I don't think you would ever want this tracked

**Comment by monicagerber** [comment]
I didn't add these because they are automatically added with `usethis::use_github()`. It might make more sense to add them in this part of the setup though. I'll test it out.

**Comment by wfulp** [comment]
For analyses we can't have on GitHub it would be nice to still ignore them.

**Comment by monicagerber** [comment]
Agree. It might have been when you set up Git (not Github), so I need to check.
