### ISSUE TITLE
Make the References section at the end of a pdf report have a section number

### ISSUE THREAD

**Issue by kelliemac** [FredHutch/VISCtemplates#123]
Currently, all of the sections of a PT report are numbered, except the references section at the end. We would like to make this section also be numbered. This will probably require updating the LaTeX template file at inst/rmarkdown/templates/visc_report/resources/template.tex

**Comment by lemireg** [comment]
It looks like the visc_report Rmd is being generated here `VISCtemplates\inst\rmarkdown\templates\visc_report\skeleton\skeleton.Rmd`
