### ISSUE TITLE
Specifying a new path with use_visc_report  fails to copy skeleton report Rmd

### ISSUE THREAD

**Issue by brborate** [FredHutch/VISCtemplates#124]
**Describe the bug**
Specifying a new path with use_visc_report  fails to copy skeleton report Rmd

**To Reproduce**
1. open Rstudio
2. run VISCtemplates::create_visc_project("tryingoutVISCtemplates")  
3. Let the Rstudio restart into the project
4. run VISCtemplates::use_visc_report("Caskey820_BAMA_PT_Report", path = "BAMA", report_type = "bama")
5. See warnings, and the template Caskey820_BAMA_PT_Report.Rmd is not created under BAMA folder.

**Expected behavior**
the template Caskey820_BAMA_PT_Report.Rmd should be created under BAMA folder, as it was the path specified while running use_visc_report().

**Comment by kelliemac** [comment]
This issue is duplicated by https://github.com/FredHutch/VISCtemplates/issues/157, see discussion there
