### ISSUE TITLE
Add acknowledgements section to standard report template

### ISSUE THREAD

**Issue by kelliemac** [FredHutch/VISCtemplates#125]
An acknowledgments section is commonly needed in VISC reports. We should add this to the standard report template.

**Comment by kelliemac** [comment]
@asatofh do you have template acknowledgements text that you would like to include (for all reports)? or is something simple like "Acknowledgments - enter acknowledgments here" good enough?

**Comment by asatofh** [comment]
> @asatofh do you have template acknowledgements text that you would like to include (for all reports)? or is something simple like "Acknowledgments - enter acknowledgments here" good enough?

@kelliemac Can you ask @drienna @sshotorb for the acknowledgement template?

**Comment by kelliemac** [comment]
As of now, here is the proposed language:

Acknowledgements

The authors thank the following individuals for their invaluable contributions to this report. 
From [insert group name or affiliation, for example: the CAVIMC/Duke team] we thank [insert individual names, and roles here, for example: Kelli Greene and Hongmei Gao (Experimental Design, Data Interpretation, Study Management); Nicole Yates (Scientific Research Laboratory Manager) and Sheetal Sawant (Biostatistician)]. 
From Fred Hutch Cancer Center, we also thank [insert names and roles here, for example: Ratana Som (SCHARP Lab Data Manager); Marie Vendettuoli and Valeria Duran (SCHARP Statistical Programmers); and Lindsey Mwoga and Drienna Holman (VISC Project Management)].

**Comment by kelliemac** [comment]
resolved by https://github.com/FredHutch/VISCtemplates/pull/153
