### ISSUE TITLE
Update BAMA methods: positivity call definition

### ISSUE THREAD

**Issue by asatofh** [FredHutch/VISCtemplates#127]
## Location
inst/templates/methods-bama/bama-statistical-methods.Rmd

## Old 

The template currently states:

* Net MFI values at the screening dilution were greater than the maximum of 100 or the 95th percentile of baseline samples (by antigen).
* Net MFI values were greater than three times the baseline background-adjusted MFI minus baseline background-adjusted blank values.
* Background-adjusted MFI values were greater than three times the baseline background-adjusted MFI values.

## New

It should read:

* Net MFI values at the screening dilution were greater than the maximum of 100 or the 95th percentile of baseline samples (by antigen).
* Net MFI values were greater than three times the baseline net MFI.
* Background-adjusted MFI values were greater than three times the baseline background-adjusted MFI values.

## Justification

We should use net MFI throughout the definition, it's not clear why we don't.

**Comment by kelliemac** [comment]
resolved by https://github.com/FredHutch/VISCtemplates/pull/144
