### ISSUE TITLE
Update background.rmd to add additional detail

### ISSUE THREAD

**Issue by asatofh** [FredHutch/VISCtemplates#128]
## Location
/inst/templates/visc-project-background.Rmd

## Old 

The template currently states:

This document should contain the study background section for {{ study_name }}.
Write project background here. Don't use headers.

> This is the old text.

## New

It should read:

[CAVD PI and number] is a [insert study title]. 

Describe trial - product, primary hypothesis. 

Describe participant enrollment - number per group planned and what those ppts received. If study was amended to reduce planned group sample sizes or study allowed for over/under enrollment such that number enrolled per group would not be the same as what is in the schema, mention it here and cite source.

Describe report - "This report presents [blinded/unblinded] [list assay] data in [list groups through what timepoints] as of [ldo_processing_date]." Note that LDO processing date comes from qdata and pdata, this may not be available depending on where this background.Rmd file exists. Anything special about the report could also be mentioned here (e.g., This PT report presents neutralization data to Tier 1A and Tier 2 versions of the vaccine strain, assessed by the TZM-bl assay. Additionally this report summarizes epitope mapping isolate pairs.")

> This is the new text.

## Justification

The current template needs a more detailed description on what to write.

**Comment by mayerbry** [comment]
The assay specific information should be in the main report Rmd because the background.Rmd document is central to all reports so it needs to be assay agnostic.

The update to the report template would therefore be something like:

````
# Background

```{r background, child=here::here("docs", "background.Rmd") }
```
"This report presents [blinded/unblinded] [list assay] data in [etc., as suggested in the issue above]
````

**Comment by kelliemac** [comment]
resolved by https://github.com/FredHutch/VISCtemplates/pull/143
