### ISSUE TITLE
Checking for empty folder when making new project

### ISSUE THREAD

**Issue by wfulp** [FredHutch/VISCtemplates#13]
For `create_visc_project` if you specify an already existing folder is it worth it to add a check that the folder is empty? Maybe a param set to not allow an empty folder, but you can change it to allow a non-empty folder is you want. I'm use to pointing to where the folder should live (the normal way to make a new project in RStudio), which sets up the project one level too high (i.e. the Projects folder), and it's a pain to move of delete all the files that get created.

**Comment by monicagerber** [comment]
`create_visc_project()` uses the same checks/workflow as `usethis::create_package()`, but with PR #78 , there is now an additional check for an empty directory and that it adheres to VISC naming convention.
