### ISSUE TITLE
Auto-generate non-empty (e.g., BAMA) report skeletons (PDF and docx) using GitHub actions

### ISSUE THREAD

**Issue by kelliemac** [FredHutch/VISCtemplates#142]
Create a GitHub action that does the following, for every pull request issued to main/master/develop, to verify that proposed changes result in report skeletons that look as expected:

1. Creates a skeleton VISC analysis project (on the GitHub servers)
2. Initializes standard reports (e.g., BAMA)
3. Compiles all reports to both PDF and docx
4. Saves PDF and docx report files as artifacts that can be viewed on GitHub to see how the skeleton PT report formatting looks (prior to study-specific customization)

Steps 1 and 2 would follow the steps in the existing package vignettes. Steps 3 and 4 would follow the steps in the existing GitHub action that renders a visc_empty skeleton report.

**Comment by slager** [comment]
Addressed by #168.
