### ISSUE TITLE
Error compiling reports to pdf in recent version of RStudio

### ISSUE THREAD

**Issue by kelliemac** [FredHutch/VISCtemplates#150]
- visc_report type Rmd fails to compile to pdf using RStudio version 2024.04.0+735 (on MacOS)
- Error message: ! LaTeX Error: Lonely \item--perhaps a missing list environment.
- Issue is in references section with \bibitem in CSLReferences environment (CSLReferences environment is defined in template.tex in VISCtemplates)
- Similar issues have been reported due to clashes between latex packages:
https://tex.stackexchange.com/questions/387937/bibentry-with-template-causes-error-lonely-item-perhaps-a-missing-list-enviro

**Comment by kelliemac** [comment]
issue is resolved by reverting to earlier version of RStudio. moving forward: next steps could be replicating the issue with the generic PT report template from VISCtemplates, then seeing if someone on windows gets the same

**Comment by kelliemac** [comment]
issue is resolved by updating the definition of CSLReferences in template.tex (see https://github.com/FredHutch/VISCtemplates/pull/159) but implications for various users (mac vs. windows, different RStudio and pandoc versions, etc.) are unknown. if you run into this issue, please post here! we have a fix that we can direct you to, but are not yet merging it to the main branch due to uncertainty about these implications

**Comment by slager** [comment]
Fixed by #159.
