### ISSUE TITLE
Long runtime for package skeleton Github action

### ISSUE THREAD

**Issue by slager** [FredHutch/VISCtemplates#165]
The package skeleton Github action takes a lot longer than the other actions.

The vast majority of that time is spent installing R packages from source:

https://github.com/FredHutch/VISCtemplates/actions/runs/9574366712/job/26397481412?pr=163

This could be greatly sped up by configuring the action to install binary R packages from the [Posit Public Package Manager](https://packagemanager.posit.co/client/#/repos/cran/setup?distribution=ubuntu-22.04&r_environment=other).

**Comment by kelliemac** [comment]
@slager I assume that PR https://github.com/FredHutch/VISCtemplates/pull/163 is the first step to addressing this?

**Comment by slager** [comment]
These things should be unrelated, because https://github.com/FredHutch/VISCtemplates/blob/main/.github/workflows/render-skeleton-rmd.yaml is using an [r-lib/actions workflow](https://github.com/FredHutch/VISCtemplates/blob/331abbba8cd8f2766396c93e38da279715fefb6b/.github/workflows/render-skeleton-rmd.yaml#L31) to install the dependency tree for VISCtemplates.  This shouldn't be calling any functions in VISCtemplates.

I am looking at the action right now and I think I see a pretty easy way to fix this.  I'll put in a PR and see if it works.

**Comment by kelliemac** [comment]
got it. sounds great, thank you!!
