### ISSUE TITLE
Abbreviate commit hash in reproducibility table

### ISSUE THREAD

**Issue by kelliemac** [FredHutch/VISCtemplates#209]
Commit hashes in reproducibility table are long, causing the table to run off the page.

Should be fixed by addressing relevant function in VISCfunction: see https://github.com/FredHutch/VISCfunctions/issues/86

Just noting here so that we don't forget to address this.

**Comment by slager** [comment]
This is related to #222.

**Comment by slager** [comment]
Fixed by https://github.com/FredHutch/VISCfunctions/pull/92.
