### ISSUE TITLE
Creates README.Rmd instead of README.md in new directory

### ISSUE THREAD

**Issue by lemireg** [FredHutch/VISCtemplates#214]
when running `VISCtemplates::create_visc_project()`

**Comment by slager** [comment]
The main advantage of having an `.Rmd` README is that you can include R code chunks in it.

To execute the code chunks and make an `.md` README from it, run `devtools::build_readme()`.

If we never need/want to have an `.Rmd` README, we could change VISCtemplates to only create an `.md` file in the first place.

Or, if we always want to render the initial `.Rmd` README template into the `.md` version, we could have VISCtemplates do that as well. But that may be redundant if the user is always going to need to update the README from the initial template anyway.

**Comment by kelliemac** [comment]
you can also render README.md from README.Rmd using the knit button.

**Comment by lemireg** [comment]
I am wondering if anyone is using the `.Rmd`. If everyone only uses `.md` file should it just be that? @kelliemac @slager 
Thanks for your feedback
