### ISSUE TITLE
Update git commit hash to short hash within Software-Package-Version-Information R chunk

### ISSUE THREAD

**Issue by brborate** [FredHutch/VISCtemplates#222]
Instead of 

`kable(
  my_session_info$packages_table, 
  format = output_type,
  booktabs = TRUE, 
  linesep = "", 
  caption = "Reproducibility software package version information"
  ) %>% 
  kable_styling(font_size = 10, latex_options = "hold_position")`

Suggest

`my_session_info$packages_table %>%
  separate(source, into = c("source1", "source2"), sep = "@", fill = "right") %>%
  mutate(
    source = if_else(
      is.na(source2),
      source1,
      paste0(source1, "@", str_sub(source2, 1, 7), ")")
    )
  ) %>%
  select(-source1, -source2) %>%
  kable(
    format = output_type,
    booktabs = TRUE,
    linesep = "",
    caption = "Reproducibility software package version information"
  ) %>%
  kable_styling(font_size = 10, latex_options = "hold_position")`

**Comment by slager** [comment]
This is related to #209.

**Comment by slager** [comment]
Fixed by https://github.com/FredHutch/VISCfunctions/pull/92.
