### ISSUE TITLE
Add test for PRs to main staying in one analysis folder (or shared folders such as docs, tests, etc)

### ISSUE THREAD

**Issue by lemireg** [FredHutch/VISCtemplates#243]
add a test and/or warning when a commit to a repo generated by VISCtemplates has work across multiple analysis folders. For example:

`https://github.com/FredHutch/Hassell750Analysis/commit/b3b9ddef3700197c896a4afe3e1fa8635b0e7a40`

which contains changes to ADCC and BAMA. (Maybe Gabby can write/implement this test? Maybe with Dave's help? Could start in just one of my own repos to demo it?)

**Comment by slager** [comment]
To me this doesn't really sound like a VISCtemplates issue, it sounds more like a git best practices issue that could be addressed in VISC/SRA git training/documentation. Specifically, git commits should be atomic, i.e. a single commit should only change one "thing".

I wouldn't advise that we try automating this. Checking that there are changes to only 1 analysis folder at a time can be done by the user right before making the commit by routinely checking `git status` prior to doing `git commit`. A pull request reviewer could also check that the list of changed files/folders in a PR only involves one analysis.

**Comment by lemireg** [comment]
ops! I meant a test for a new PR to `main`/`master` (not a commit). Do you still think it's not something to test @slager ?

**Comment by slager** [comment]
Yeah, in my opinion it sounds more like something that would go in SRA best practices documentation/training, or on a checklist for what to look at before merging a PR, rather than something that we'd want to make explicit automated tests for.

**Comment by slager** [comment]
Closing at not planned per Slack discussion with @lemireg today.
