### ISSUE TITLE
Move code out of template skeleton and into R folder where possible

### ISSUE THREAD

**Issue by wfulp** [FredHutch/VISCtemplates#29]
Much of the skeleton code can be simplified by making functions. Specifically the `package-loading-and-options` and the `word-pdf-functions` chunks can be simplified.

**Comment by mayerbry** [comment]
we should make just these functions in the VISCtemplates package, that way they can be subject to testing and better version control.

**Comment by wfulp** [comment]
These have all been moved over to VISCtemplates functions #40
