### ISSUE TITLE
barebones template for non-standard reports (and SAPs)

### ISSUE THREAD

**Issue by mayerbry** [FredHutch/VISCtemplates#45]
For analyses or write-ups that don't follow the typical PT report templates it'd be nice to be able to generate from a minimal template like "visc_minimal" or something. It would include just:
- yaml
- a chunk for loading packages and setting chunk options
- data chunk?
- reproducibility tables

and any other boilerplate stuff I'm forgetting?

I think this would be a nice bridge solution without having to think too deeply about non-standard report or SAP structures.

**Comment by monicagerber** [comment]
Closed with #53
