### ISSUE TITLE
function to generate report files and folder

### ISSUE THREAD

**Issue by mayerbry** [FredHutch/VISCtemplates#51]
would be nice if there was a wrapper like:
`create_visc_report(path = 'BAMA/BAMA_IgG_pt_report.Rmd', template = 'visc_report')`

that does the following on the backend:
```
usethis::use_directory("BAMA")

rmarkdown::draft(
  "BAMA/BAMA_IgG_pt_report.Rmd", 
  template = "visc_report", 
  package = "VISCtemplates", 
  edit = FALSE
  )

```

template could specify `visc_report` as default, so only path is necessary argument.

**Comment by wfulp** [comment]
That was be useful. I propose having `edit = TRUE` though, which I believe will pop open the report in the source panel.

**Comment by wfulp** [comment]
Is it worth it to add `package` or `edit` params to pass through to `draft` (or just use `...`)? If you can set `package` then this wrapper could be used for non-VISCtemplates templates

**Comment by monicagerber** [comment]
`create_visc_report()` is in release 1.0.0. It creates a report template and "child" R Markdown docs for the assay you select. You'll still have to specify the path where you want to save the report (it doesn't include something like `usethis::use_directory("BAMA")`). For more details, see the vignette: `vignette("using_pdf_and_word_template")`.
