### ISSUE TITLE
Word document numbering happens twice on new Pandoc versions

### ISSUE THREAD

**Issue by wfulp** [FredHutch/VISCtemplates#67]
![Screenshot 2020-12-29 182353](https://user-images.githubusercontent.com/12237512/103325974-1a357380-4a03-11eb-866b-0d28c081ca79.png)

I think the `word-styles-reference.docx` file needs an update

**Comment by kelliemac** [comment]
Resolved by https://github.com/FredHutch/VISCtemplates/pull/134
