### ISSUE TITLE
Error with use_visc_docs()

### ISSUE THREAD

**Issue by monicagerber** [FredHutch/VISCtemplates#77]
` Error in if (key$key[h] != key$key[i]) { : argument is of length zero `

**Comment by monicagerber** [comment]
This error occurs with `use_bib()`. When I remove the double brackets from `{{R Core Team}}` ([line 454](https://github.com/FredHutch/VISCtemplates/blob/1807e44b836d320495d6c96c15a7392abcbc42c5/inst/templates/bibliography.bib#L454)), I no longer get the error. However, the double brackets are needed for the citation, otherwise it gets cited as "Team, R Core".

```
> citation()

To cite R in publications use:

  R Core Team (2020). R: A language and
  environment for statistical computing. R
  Foundation for Statistical Computing, Vienna,
  Austria. URL https://www.R-project.org/.

A BibTeX entry for LaTeX users is

  @Manual{,
    title = {R: A Language and Environment for Statistical Computing},
    author = {{R Core Team}},
    organization = {R Foundation for Statistical Computing},
    address = {Vienna, Austria},
    year = {2020},
    url = {https://www.R-project.org/},
  }

We have invested a lot of time and effort in
creating R, please cite it when using it for data
analysis. See also ‘citation("pkgname")’ for
citing R packages.
```

**Comment by wfulp** [comment]
After a ton of Goggling and trial and error I finally found a solution :)

`author = "{R Core Team}"`

**Comment by monicagerber** [comment]
This works, thanks Jimmy!
