### ISSUE TITLE
Remove SST table in project-level README

### ISSUE THREAD

**Issue by monicagerber** [FredHutch/VISCtemplates#80]
When you use `create_visc_project()` to create a new analysis project, it populates with a README. The README has a table where we can keep track of SST, but I don't think we need this anymore.

Instead, we track this with the SST Log (FRM-0105).

@asatofh are you ok with this proposed change to the README?

**Comment by asatofh** [comment]
The SST Determination Log identifies what study materials should be trained on and who should fill out training documentation, but it doesn't track whether the people assigned to do this actually do it. The lead SRA is responsible for making sure everyone fills out SSTs based on the SST determination log, so this table on Github could be one way to do it.
