### ISSUE TITLE
Remove "Lab Spec." "Data Spec." from report README?

### ISSUE THREAD

**Issue by monicagerber** [FredHutch/VISCtemplates#95]
I think we need to update the report-level [README template](https://github.com/FredHutch/VISCtemplates/blob/master/inst/rmarkdown/templates/visc_report/resources/README_PT_Report.md) to reflect current data processing practices and updates to VISCtemplates. Currently, SRAs are encouraged to note the Data Spec and Lab Spec version from [VISC-Assay-Methods](https://github.com/FredHutch/VISC-Assay-Methods) in a table in the report README. 

1) @mayerbry Templates for lab methods will be available with the next release of VISCtemplates. The VISCtemplates version will be populated in the lab methods template, see #88, [bama-lab-methods.Rmd](https://github.com/FredHutch/VISCtemplates/blob/cb6e643e2ceeba1d5b54dc0d6239778533a03a60/inst/templates/methods-bama/bama-lab-methods.Rmd). I propose removing "lab spec." from the README, do you agree?

2) Does the "Data Spec." version still make sense? Or should we include a version number from one of the STP packages, for example, scharpbama or  scharpimmunotemplates? @mariev and @asatofh, please let me know what you think about this.

**Comment by asatofh** [comment]
> 2\. Does the "Data Spec." version still make sense? Or should we include a version number from one of the STP packages, for example, scharpbama or scharpimmunotemplates?

Interesting suggestion. On the one hand, for NAb and BAMA at least, referencing the scharpbama or scharpnab processing specs or vignette would force the author to acknowledge the applicability of those specifications. Less clear what to do about other assays. However, the reality is that SRAs generally skipped this step, so we either need more clear instructions in a workflow of when to document specifications in the README, or we should drop the field from the table.

**Comment by monicagerber** [comment]
Thanks @asatofh! Based on your comment and our conversation today, this is how I think we can solve this issue:

- We'll keep the "Data Spec" column. If there's a data spec, the SRA can link to the document or scharpbama/scharpnab package.
- I'll remove "Lab Spec" because this will automatically be documented with VISCtemplates in the next release.
